name: checker
on:
  push:

jobs:
  other-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - run: ls -la

      - name: Checkout ziti-sdk-swift
        uses: actions/checkout@v3
        with:
          repository: openziti/ziti-sdk-swift
      - run: ls -la
