name: CI
on: [ push ]

jobs:
  ziti-action:
    runs-on: macos-latest
    name: Test Ziti Action
    steps:
    - name: Ziti Action 
      id: hello
      uses: smilindave26/ziti-test-action@v0.0.2
      with:
        who-to-greet: 'Ziggy'
