name: Release Drafter

on:
  push:
    branches:
      - main

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
    - name: Draft Release
      id: release_drafter
      uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Show Some Stuff
      run: |
        echo ${{ steps.release_drafter.outputs.name }}
        echo ${{ steps.release_drafter.outputs.tag_name }}
        echo ${{ steps.release_drafter.outputs.upload_url }}

    - name: Make Something
      run: echo "hello tag ${{ steps.release_drafter.outputs.tag_name }}" > hello.txt

    - name: Upload it
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release_drafter.outputs.upload_url }}
        asset_path: ./hello.txt
        asset_name: hello.txt
        asset_content_type: text/plain
