name: ziti-webhook
on: [ push ]

jobs:
  ziti-action:
    runs-on: macos-latest
    name: Test Ziti Action
    steps:
    - uses: openziti/ziti-webhook-action@main
      with:
        ziti-id: ${{ secrets.ZITI_WEBHOOK_ACTION_ID }}
        webhook-url: 'https://httpbin.ziti/post'
        webhook-secret: ${{ secrets.ZITI_WEBHOOK_SECRET }}
      env:
        ZITI_LOG: 3
        ZITI_NODEJS_LOG: 3
